version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 15
  rebase-strategy: disabled
