Inflecto.inflections do |inflect|
  inflect.irregular "broadcast_sms", "broadcast_smses"
  inflect.irregular "division_member_preferences", "division_members_preferences"
  inflect.irregular "division_preferences", "divisions_preferences"
  inflect.irregular "member_preferences", "member_preferences"
  inflect.irregular "member_preferences", "members_preferences"
  inflect.irregular "opponent_results", "opponent_results"
  inflect.irregular "opponent_results", "opponents_results"
  inflect.irregular "team_preferences", "team_preferences"
  inflect.irregular "team_preferences", "teams_preferences"
  inflect.irregular "team_results", "team_results"
  inflect.irregular "team_results", "teams_results"
  inflect.irregular "partner_preferences", "partner_preferences"
  inflect.irregular "partner_preferences", "partners_preferences"
end
